server:
  port: 8833
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frame?serverTimezone=UTC
    username: root
    password: lucas
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.zpark.core.model
  mapper-locations: classpath:mapper/*.xml